use super::{DesktopProfile, DisplayManager, DisplayServer, OptionalPackage, Profile, ProfileKind};

/// Helper to keep desktop profile literals concise.
#[allow(clippy::too_many_arguments)]
fn desktop(
    name: &'static str,
    display_name: &'static str,
    packages: Vec<&'static str>,
    display_server: DisplayServer,
    default_display_manager: Option<DisplayManager>,
    needs_seat_access: bool,
    sddm_session: Option<&'static str>,
    optional_packages: Vec<OptionalPackage>,
) -> Profile {
    Profile {
        name,
        display_name,
        description: "",
        packages,
        services: Vec::new(),
        user_services: Vec::new(),
        post_install_steps: Vec::new(),
        kind: ProfileKind::Desktop(DesktopProfile {
            display_server,
            default_display_manager,
            needs_seat_access,
            sddm_session,
            optional_packages,
        }),
    }
}

/// Convenience: build a `Vec<OptionalPackage>` from `(package, description)`
/// pairs. Pass an empty description to leave it blank.
fn opts(pkgs: &[(&'static str, &'static str)]) -> Vec<OptionalPackage> {
    pkgs.iter()
        .map(|(p, d)| OptionalPackage::with_desc(p, d))
        .collect()
}

pub fn desktop_profiles() -> Vec<Profile> {
    use DisplayManager::*;
    use DisplayServer::*;

    vec![
        // Bare X server with no DE/WM/DM. Use this when you want to install
        // X yourself or pair it with a window manager that isn't packaged
        // here. Mirrors upstream archinstall's `Xorg` top-level profile.
        desktop(
            "xorg",
            "Xorg (bare)",
            vec!["xorg-server", "xorg-xinit"],
            Xorg,
            None,
            false,
            None,
            Vec::new(),
        ),
        desktop(
            "gnome",
            "GNOME",
            vec!["gnome", "gnome-tweaks"],
            Both,
            Some(Gdm),
            false,
            None,
            opts(&[
                (
                    "gnome-extra",
                    "Extra GNOME apps (Maps, Weather, Calendar, …)",
                ),
                ("gnome-software", "Software centre with Flatpak support"),
                ("flatpak", "Sandboxed application runtime"),
            ]),
        ),
        desktop(
            "kde",
            "KDE Plasma",
            vec![
                "plasma-desktop",
                "konsole",
                "kate",
                "dolphin",
                "ark",
                "plasma-workspace",
            ],
            Both,
            Some(Sddm),
            false,
            Some("plasma"),
            opts(&[
                (
                    "kde-applications",
                    "Full KDE application suite (Okular, Gwenview, …)",
                ),
                ("flatpak", "Sandboxed application runtime"),
                ("discover", "KDE software centre"),
            ]),
        ),
        desktop(
            "xfce",
            "Xfce",
            vec!["xfce4", "xfce4-goodies", "pavucontrol", "gvfs", "xarchiver"],
            Xorg,
            Some(Lightdm),
            false,
            None,
            opts(&[
                ("thunar", "File manager"),
                ("mousepad", "Lightweight text editor"),
                ("ristretto", "Image viewer"),
            ]),
        ),
        desktop(
            "cinnamon",
            "Cinnamon",
            vec![
                "cinnamon",
                "system-config-printer",
                "gnome-keyring",
                "gnome-terminal",
                "engrampa",
                "gnome-screenshot",
                "gvfs-smb",
                "xed",
                "xdg-user-dirs-gtk",
            ],
            Xorg,
            Some(Lightdm),
            false,
            None,
            Vec::new(),
        ),
        desktop(
            "budgie",
            "Budgie",
            vec![
                "materia-gtk-theme",
                "budgie",
                "mate-terminal",
                "nemo",
                "papirus-icon-theme",
            ],
            Xorg,
            Some(Lightdm),
            false,
            None,
            Vec::new(),
        ),
        desktop(
            "mate",
            "MATE",
            vec!["mate", "mate-extra"],
            Xorg,
            Some(Lightdm),
            false,
            None,
            Vec::new(),
        ),
        desktop(
            "deepin",
            "Deepin",
            vec!["deepin", "deepin-terminal", "deepin-editor"],
            Xorg,
            Some(Lightdm),
            false,
            None,
            Vec::new(),
        ),
        desktop(
            "lxqt",
            "LXQt",
            vec![
                "lxqt",
                "breeze-icons",
                "oxygen-icons",
                "xdg-utils",
                "ttf-freefont",
                "l3afpad",
                "slock",
            ],
            Xorg,
            Some(Sddm),
            false,
            Some("lxqt"),
            Vec::new(),
        ),
        desktop(
            "hyprland",
            "Hyprland",
            vec![
                "hyprland",
                "dunst",
                "kitty",
                "uwsm",
                "dolphin",
                "wofi",
                "xdg-desktop-portal-hyprland",
                "qt5-wayland",
                "qt6-wayland",
                "polkit-kde-agent",
                "grim",
                "slurp",
            ],
            Wayland,
            Some(Sddm),
            true,
            Some("hyprland"),
            opts(&[
                ("hyprpaper", "Wallpaper utility from the Hyprland project"),
                ("hypridle", "Idle daemon (auto-lock, dim, sleep)"),
                ("hyprlock", "Screen locker"),
                ("swww", "Animated wallpaper daemon"),
                ("mako", "Wayland notification daemon"),
                ("wl-clipboard", "Clipboard helper (wl-copy / wl-paste)"),
            ]),
        ),
        desktop(
            "sway",
            "Sway",
            vec![
                "sway",
                "swaybg",
                "swaylock",
                "swayidle",
                "waybar",
                "wmenu",
                "brightnessctl",
                "grim",
                "slurp",
                "pavucontrol",
                "foot",
                "xorg-xwayland",
            ],
            Wayland,
            Some(Lightdm),
            true,
            Some("sway"),
            opts(&[
                (
                    "swaylock-effects",
                    "swaylock fork with blur/screenshot effects",
                ),
                ("wl-clipboard", "Clipboard helper (wl-copy / wl-paste)"),
                ("mako", "Wayland notification daemon"),
            ]),
        ),
        desktop(
            "i3",
            "i3",
            vec![
                "i3-wm",
                "i3lock",
                "i3status",
                "i3blocks",
                "xss-lock",
                "xterm",
                "lightdm-gtk-greeter",
                "dmenu",
            ],
            Xorg,
            Some(Lightdm),
            false,
            Some("i3"),
            opts(&[
                ("polybar", "Modular status bar"),
                ("rofi", "Application launcher and dmenu replacement"),
                ("feh", "Image viewer often used to set wallpaper"),
                ("nitrogen", "Graphical wallpaper setter"),
            ]),
        ),
        desktop(
            "cosmic",
            "COSMIC",
            vec!["cosmic", "xdg-user-dirs"],
            Wayland,
            Some(CosmicGreeter),
            false,
            None,
            Vec::new(),
        ),
        desktop(
            "enlightenment",
            "Enlightenment",
            vec![
                "enlightenment",
                "terminology",
                "lightdm-gtk-greeter",
                "xdg-user-dirs",
            ],
            Xorg,
            Some(Lightdm),
            false,
            None,
            Vec::new(),
        ),
        desktop(
            "awesome",
            "Awesome",
            vec![
                "awesome",
                "xterm",
                "lightdm-gtk-greeter",
                "dmenu",
                "picom",
                "xdg-user-dirs",
            ],
            Xorg,
            Some(Lightdm),
            false,
            None,
            Vec::new(),
        ),
        desktop(
            "bspwm",
            "Bspwm",
            vec![
                "bspwm",
                "sxhkd",
                "xterm",
                "lightdm-gtk-greeter",
                "dmenu",
                "picom",
                "xdg-user-dirs",
            ],
            Xorg,
            Some(Lightdm),
            false,
            None,
            Vec::new(),
        ),
        desktop(
            "labwc",
            "LabWC",
            vec![
                "labwc",
                "waybar",
                "foot",
                "fuzzel",
                "xdg-desktop-portal-wlr",
                "xdg-user-dirs",
            ],
            Wayland,
            Some(Sddm),
            true,
            Some("labwc"),
            Vec::new(),
        ),
        desktop(
            "niri",
            "Niri",
            vec![
                "niri",
                "foot",
                "fuzzel",
                "waybar",
                "xdg-desktop-portal-gnome",
                "xwayland-satellite",
                "xdg-user-dirs",
            ],
            Wayland,
            Some(Sddm),
            true,
            Some("niri"),
            Vec::new(),
        ),
        desktop(
            "qtile",
            "Qtile",
            vec![
                "qtile",
                "xterm",
                "lightdm-gtk-greeter",
                "dmenu",
                "xdg-user-dirs",
            ],
            Xorg,
            Some(Lightdm),
            false,
            None,
            Vec::new(),
        ),
        desktop(
            "river",
            "River",
            vec![
                "river",
                "foot",
                "fuzzel",
                "waybar",
                "xdg-desktop-portal-wlr",
                "xdg-user-dirs",
            ],
            Wayland,
            Some(Sddm),
            true,
            Some("river"),
            Vec::new(),
        ),
        desktop(
            "xmonad",
            "XMonad",
            vec![
                "xmonad",
                "xmonad-contrib",
                "xterm",
                "lightdm-gtk-greeter",
                "dmenu",
                "xdg-user-dirs",
            ],
            Xorg,
            Some(Lightdm),
            false,
            None,
            Vec::new(),
        ),
    ]
}
