use std::fs;
use std::path::Path;

use color_eyre::eyre::{Context, Result};

use crate::system::cmd::{CommandRunner, check_exit, chroot_cmd};

/// Configure automatic login for the given user on the detected display manager.
///
/// Supported DMs and their config locations:
/// - `gdm`          → `/etc/gdm/custom.conf`
/// - `sddm`         → `/etc/sddm.conf.d/autologin.conf`
/// - `lightdm`      → `/etc/lightdm/lightdm.conf.d/12-autologin.conf`
///   (also adds user to the `autologin` group)
/// - `ly`           → `/etc/ly/config.ini`
/// - `cosmic-greeter` → not yet supported (config format still unstable)
///
/// `session` is only used by SDDM; pass `None` to let SDDM pick its default.
pub fn configure(
    runner: &dyn CommandRunner,
    target: &Path,
    dm: &str,
    username: &str,
    session: Option<&str>,
) -> Result<()> {
    match dm {
        "gdm" => configure_gdm(target, username),
        "sddm" => configure_sddm(target, username, session.unwrap_or("")),
        "lightdm" => configure_lightdm(runner, target, username),
        "ly" => configure_ly(target, username),
        "cosmic-greeter" => {
            tracing::warn!("autologin for cosmic-greeter is not yet supported");
            Ok(())
        }
        other => {
            tracing::warn!(dm = other, "unknown display manager, skipping autologin");
            Ok(())
        }
    }
}

/// GDM — `/etc/gdm/custom.conf`
/// https://help.gnome.org/admin/gdm/stable/configuration.html
fn configure_gdm(target: &Path, username: &str) -> Result<()> {
    let conf_dir = target.join("etc/gdm");
    fs::create_dir_all(&conf_dir).wrap_err("failed to create /etc/gdm")?;

    let content = format!(
        "# Generated by archinstall-zfs\n\
         [daemon]\n\
         AutomaticLoginEnable=True\n\
         AutomaticLogin={username}\n"
    );

    fs::write(conf_dir.join("custom.conf"), content).wrap_err("failed to write gdm custom.conf")?;

    tracing::info!(username, "configured GDM autologin");
    Ok(())
}

/// SDDM — `/etc/sddm.conf.d/autologin.conf`
/// https://wiki.archlinux.org/title/SDDM#Autologin
fn configure_sddm(target: &Path, username: &str, session: &str) -> Result<()> {
    let conf_dir = target.join("etc/sddm.conf.d");
    fs::create_dir_all(&conf_dir).wrap_err("failed to create /etc/sddm.conf.d")?;

    let content = format!(
        "# Generated by archinstall-zfs\n\
         [Autologin]\n\
         User={username}\n\
         Session={session}\n"
    );

    fs::write(conf_dir.join("autologin.conf"), content)
        .wrap_err("failed to write sddm autologin.conf")?;

    tracing::info!(username, session, "configured SDDM autologin");
    Ok(())
}

/// LightDM — `/etc/lightdm/lightdm.conf.d/12-autologin.conf`
/// https://wiki.archlinux.org/title/LightDM#Enabling_autologin
///
/// LightDM also requires the user to be a member of the `autologin` group.
fn configure_lightdm(runner: &dyn CommandRunner, target: &Path, username: &str) -> Result<()> {
    let conf_dir = target.join("etc/lightdm/lightdm.conf.d");
    fs::create_dir_all(&conf_dir).wrap_err("failed to create lightdm conf.d")?;

    let content = format!(
        "# Generated by archinstall-zfs\n\
         [Seat:*]\n\
         autologin-user={username}\n\
         autologin-user-timeout=0\n"
    );

    fs::write(conf_dir.join("12-autologin.conf"), content)
        .wrap_err("failed to write lightdm autologin conf")?;

    // Create the autologin group and add the user — LightDM requires it.
    let _ = chroot_cmd(runner, target, "groupadd", &["-f", "autologin"]);
    let output = chroot_cmd(runner, target, "usermod", &["-aG", "autologin", username])?;
    check_exit(&output, &format!("add {username} to autologin group"))?;

    tracing::info!(username, "configured LightDM autologin");
    Ok(())
}

/// Ly — `/etc/ly/config.ini`
/// https://github.com/fairyglade/ly
fn configure_ly(target: &Path, username: &str) -> Result<()> {
    let conf_dir = target.join("etc/ly");
    fs::create_dir_all(&conf_dir).wrap_err("failed to create /etc/ly")?;

    // Ly's config is a simple key = value file. Write only the autologin key;
    // the rest of the defaults ship with the package.
    let content = format!(
        "# Generated by archinstall-zfs\n\
         [ly]\n\
         autologin = {username}\n"
    );

    fs::write(conf_dir.join("config.ini"), content).wrap_err("failed to write ly config.ini")?;

    tracing::info!(username, "configured Ly autologin");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::system::cmd::tests::{CannedResponse, RecordingRunner};

    #[test]
    fn test_configure_gdm() {
        let dir = tempfile::tempdir().unwrap();
        let runner = RecordingRunner::new(vec![]);
        configure(&runner, dir.path(), "gdm", "alice", None).unwrap();

        let content = fs::read_to_string(dir.path().join("etc/gdm/custom.conf")).unwrap();
        assert!(content.contains("AutomaticLoginEnable=True"));
        assert!(content.contains("AutomaticLogin=alice"));
    }

    #[test]
    fn test_configure_sddm_with_session() {
        let dir = tempfile::tempdir().unwrap();
        let runner = RecordingRunner::new(vec![]);
        configure(&runner, dir.path(), "sddm", "bob", Some("plasma")).unwrap();

        let content =
            fs::read_to_string(dir.path().join("etc/sddm.conf.d/autologin.conf")).unwrap();
        assert!(content.contains("User=bob"));
        assert!(content.contains("Session=plasma"));
    }

    #[test]
    fn test_configure_lightdm() {
        // groupadd + usermod
        let responses: Vec<CannedResponse> = (0..2).map(|_| CannedResponse::default()).collect();
        let runner = RecordingRunner::new(responses);
        let dir = tempfile::tempdir().unwrap();
        configure(&runner, dir.path(), "lightdm", "carol", None).unwrap();

        let content = fs::read_to_string(
            dir.path()
                .join("etc/lightdm/lightdm.conf.d/12-autologin.conf"),
        )
        .unwrap();
        assert!(content.contains("autologin-user=carol"));
        assert!(content.contains("autologin-user-timeout=0"));

        let calls = runner.calls();
        assert!(
            calls
                .iter()
                .any(|c| c.args.iter().any(|a| a == "autologin"))
        );
    }

    #[test]
    fn test_configure_ly() {
        let dir = tempfile::tempdir().unwrap();
        let runner = RecordingRunner::new(vec![]);
        configure(&runner, dir.path(), "ly", "dave", None).unwrap();

        let content = fs::read_to_string(dir.path().join("etc/ly/config.ini")).unwrap();
        assert!(content.contains("autologin = dave"));
    }
}
